### ISSUE TITLE
ESP disconnected

### ISSUE THREAD

**Issue by xlfe** [xlfe/radiale#2]
```
2022-04-01T10:00:00.011Z debsvc DEBUG [radiale.core:70] - :radiale.core/desc Do it
2022-04-01T10:00:00.011Z debsvc DEBUG [radiale.core:70] - :radiale.schedule/params {:tz "Australia/Sydney", :day_of_week "*", :hour 21, :minute 0}
2022-04-01T10:00:00.011Z debsvc DEBUG [radiale.core:70] - :radiale.core/then {:radiale.core/fn #object[sci.impl.fns$fun$arity_3__7895 0x5f981ef5 "sci.impl.f
ns$fun$arity_3__7895@5f981ef5"], :radiale.esp/state true, :radiale.esp/ident :switch-a/primary}
2022-04-01T10:00:00.012Z debsvc DEBUG [radiale.core:72] - 


Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/radiale/pod.py", line 123, in run_pod
    await self.invoke(msg)
  File "/usr/local/lib/python3.9/site-packages/radiale/pod.py", line 184, in invoke
    await esphome.switch_command(self.out, id, client, opts['key'], opts['state'])
  File "/usr/local/lib/python3.9/site-packages/radiale/esphome.py", line 41, in switch_command
    await client.switch_command(key, state)
  File "/usr/local/lib/python3.9/site-packages/aioesphomeapi/client.py", line 529, in switch_command
    self._check_authenticated()
  File "/usr/local/lib/python3.9/site-packages/aioesphomeapi/client.py", line 232, in _check_authenticated
    self._check_connected()
  File "/usr/local/lib/python3.9/site-packages/aioesphomeapi/client.py", line 227, in _check_connected
    raise APIConnectionError(f"Not connected to {self._log_name}!")
aioesphomeapi.core.APIConnectionError: Not connected to X.X.X.X!
```

**Comment by xlfe** [comment]
leverage https://github.com/esphome/aioesphomeapi/blob/1eebbfc1e07bd4b1953de2fa85c78da6ad3a11f7/aioesphomeapi/log_reader.py#L65
