### ISSUE TITLE
fails to reconnect

### ISSUE THREAD

**Issue by xlfe** [xlfe/radiale#4]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/radiale/pod.py", line 127, in run_pod
    await self.invoke(msg)
  File "/usr/local/lib/python3.9/site-packages/radiale/pod.py", line 241, in invoke
    await service.service_command(id, opts['key'], opts['params'])
  File "/usr/local/lib/python3.9/site-packages/radiale/esphome.py", line 129, in service_command
    await self.cli.execute_service(service, params)
  File "/usr/local/lib/python3.9/site-packages/aioesphomeapi/client.py", line 661, in execute_service
    self._check_authenticated()
  File "/usr/local/lib/python3.9/site-packages/aioesphomeapi/client.py", line 235, in _check_authenticated
    raise APIConnectionError(f"Not authenticated for {self._log_name}!")
aioesphomeapi.core.APIConnectionError: Not authenticated for X.X.X.X!

**Comment by xlfe** [comment]
```
ESP Connecting keypad
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aioesphomeapi/connection.py", line 409, in send_message_await_response_complex
    await asyncio.wait_for(fut, timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/radiale/pod.py", line 127, in run_pod
    await self.invoke(msg)
  File "/usr/local/lib/python3.9/site-packages/radiale/pod.py", line 221, in invoke
    await asyncio.create_task(svc.update_services())
  File "/usr/local/lib/python3.9/site-packages/radiale/esphome.py", line 97, in update_services
    sensors = await self.cli.list_entities_services()
  File "/usr/local/lib/python3.9/site-packages/aioesphomeapi/client.py", line 277, in list_entities_services
    resp = await self._connection.send_message_await_response_complex(
  File "/usr/local/lib/python3.9/site-packages/aioesphomeapi/connection.py", line 411, in send_message_await_response_complex
    raise TimeoutAPIError(
aioesphomeapi.core.TimeoutAPIError: Timeout waiting for response for <class 'api_pb2.ListEntitiesRequest'>
  
ERROR:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/radiale/pod.py", line 127, in run_pod
    await self.invoke(msg)
  File "/usr/local/lib/python3.9/site-packages/radiale/pod.py", line 241, in invoke
    await service.service_command(id, opts['key'], opts['params'])
  File "/usr/local/lib/python3.9/site-packages/radiale/esphome.py", line 126, in service_command
    svc = self.service_details[str(key)].copy()
AttributeError: 'ESPHome' object has no attribute 'service_details'

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/radiale/pod.py", line 127, in run_pod
    await self.invoke(msg)
  File "/usr/local/lib/python3.9/site-packages/radiale/pod.py", line 241, in invoke
    await service.service_command(id, opts['key'], opts['params'])
  File "/usr/local/lib/python3.9/site-packages/radiale/esphome.py", line 126, in service_command
    svc = self.service_details[str(key)].copy()
AttributeError: 'ESPHome' object has no attribute 'service_details'

```
